import Head from "next/head";
import PostForm from "@/Components/postForm";
import Discussion from "@/Components/discussion";
import { useAppSelector } from "@/Components/store";

export default function Home() {
  var allDiscussion = useAppSelector((state) => state.disSlice.alldis);
  const sortedList =[...allDiscussion]
  sortedList.sort(function(a, b){return b.date - a.date});
  const discussionsList = sortedList.map(
    ({ id, date, user, text, likes, iLikedIt, replies }) => (
      <Discussion
        allDiscussions={allDiscussion}
        key={id}
        did={id}
        date={date}
        user={user}
        text={text}
        likes={likes}
        iLikedIt={iLikedIt}
        replies={replies}
      />
    )
  );

  return (
    <>
      <Head>
        <title>Discussion</title>
        <meta name="description" content="Generated by M:R" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-white w-full p-12 h-screen">
        <PostForm />
        <div className="pb-32">{discussionsList}</div>
      </section>
    </>
  );
}
