import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import PostForm from "@/Components/postForm";
import Discussion from "@/Components/discussion";
import { idText } from "typescript";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });
interface IUser {
  name: string;
  avatar?: string;
}
interface IComment {
  id: number;
  date: number; // unix timestamp in milliseconds.
  user: IUser;
  text: string;
  likes: number;
  iLikedIt: boolean;
}
interface IDiscussion extends IComment {
  replies: IComment[];
}
interface IProps {
  comments: IComment[];
}



export default function Home() {
  const [fetchedDis, setFetchedDis] = useState<IDiscussion[]>([]);
  useEffect(() => {
    fetch("http://localhost:3000/api/discussions")
      .then((res) => res.json())
      .then((data) => setFetchedDis(data));
     
  }, []);
  const disscussionsList = fetchedDis.map(
    ({ id, date, user, text, likes, iLikedIt, replies }) => (
      <Discussion
        id={id}
        date={date}
        user={user}
        text={text}
        likes={likes}
        iLikedIt={iLikedIt}
        replies={replies}
      />
    )
  );
  return (
    <>
      <Head>
        <title>Disscussion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-white w-full p-12 h-screen">
        <PostForm />
        <div className="pb-32">{disscussionsList}</div>
      </section>
    </>
  );
}
