import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import PostForm from "@/Components/postForm";
import Discussion from "@/Components/discussion";
import { idText } from "typescript";

const inter = Inter({ subsets: ["latin"] });
interface IUser {
  name: string;
  avatar?: string;
}
interface IComment {
  id: number;
  date: number; // unix timestamp in milliseconds.
  user: IUser;
  text: string;
  likes: number;
  iLikedIt: boolean;
}
interface IDiscussion extends IComment {
  replies: IComment[];
}
interface IProps {
  comments: IComment[];
}
const discussions: IDiscussion[] = [
  {
    id: 3,
    date: 1672576574000,
    user: {
      name: "Bessie Cooper",
      avatar:
        "https://www.godaddy.com/garage/wp-content/uploads/judith-kallos-BW-NEW-150x150.jpg",
    },
    text: "I think for our second compaign we can try to target a different audience. How does it sound for you?",
    likes: 2,
    iLikedIt: false,
    replies: [
      {
        id: 5,
        date: 1672581014000,
        user: {
          name: "Marvin McKinney",
          avatar:
            "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50",
        },
        text: "Yes, that sounds good! I can think about this tomorrow. When do we plan to start that compaign?",
        likes: 3,
        iLikedIt: true,
      },
      {
        id: 6,
        date: 1672581614000,
        user: {
          name: "Bessie Cooper",
          avatar:
            "https://www.godaddy.com/garage/wp-content/uploads/judith-kallos-BW-NEW-150x150.jpg",
        },
        text: "We plan to run the compaign on Friday - as far as I know. Do you think you will get this done by Thursday @Marvin?",
        likes: 0,
        iLikedIt: false,
      },
    ],
  },
  {
    id: 2,
    date: 1672232414000,
    user: {
      name: "Marvin McKinney",
      avatar:
        "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50",
    },
    text: "The first compaign went smoothly. Please make sure to see all attachments with the results to understand the flow.",
    likes: 2,
    iLikedIt: false,
    replies: [],
  },
  {
    id: 1,
    date: 1671886814000,
    user: {
      name: "Savannah Nguyen",
    },
    text: "We have just published the first campaign. Let's see the results in the 5 days and we will iterate on this.",
    likes: 50,
    iLikedIt: true,
    replies: [],
  },
];

const { id, date, user, text, likes, iLikedIt, replies } = discussions[0];
export default function Home() {
  return (
    <>
      <Head>
        <title>Disscussion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white w-full p-12 h-screen">
        <PostForm />
        <Discussion
          id={id}
          date={date}
          user={user}
          text={text}
          likes={likes}
          iLikedIt={iLikedIt}
          replies={replies}
        />
      </main>
    </>
  );
}
